package emitter

import (
	"encoding/json"
	"fmt"
	"log"

	"github.com/morhekil/goratio/feeder/data"
)

// Pull accepts a channel generated by a collector, and emits
// it into the destination storage
func Pull(c chan *data.Event) {
	for e := range c {
		e.Hydrate()
		s, err := json.Marshal(e)
		if err != nil {
			log.Fatal(err)
		}
		fmt.Printf("%s\n", s)
	}
}
